version: '2'
services:
    web:
        build: .
        image: gaggle
        ports:
            - "8080:8080"
        volumes:
            - ./movie:/usr/src/movie
            - ./database:/usr/src/database
        links:
            - db
    db:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql:rw
        environment:
            MYSQL_ROOT_PASSWORD: supersecretpassword
            MYSQL_DATABASE: gaggle
            MYSQL_USER: gaggle
            MYSQL_PASSWORD: gaggle